### ISSUE TITLE
Mapputnik remplace les variables et URLs "locales"

### ISSUE THREAD

**Issue by gqdc** [utagawal/MTBmaptiles#2]
Les URLs "mbtiles", et les variables sont modifiées dans le fichier json généré via Mapputnik.
Solutions : ajouter des fonctions de contrôles et de corrections dans update_glstyle.sh

**Comment by utagawal** [comment]
Voir ici pour changer les chaines de caractères lors du déploiement https://stackoverflow.com/questions/11392478/how-to-replace-a-string-in-multiple-files-in-linux-command-line

**Comment by gqdc** [comment]
fixed on bb05953
