### ISSUE TITLE
Add Glyphs

### ISSUE THREAD

**Issue by utagawal** [utagawal/MTBmaptiles#6]
New symbols needed for :
* Cave : https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/natural/cave.svg
* Cliffs : https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/cliff2.svg
* Saddle : https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/natural/saddle.svg
* Wetland : https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/generating_patterns
* Rock overlay :  https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/generating_patterns/rock.svg
* Military pattern : https://github.com/gravitystorm/openstreetmap-carto/blob/master/patterns/military_red_hatch.svg

**Comment by gqdc** [comment]
The new wetland.svg has been renamed to *wetland-gravitystorm.svg*

Documentation has been updated

**Comment by gqdc** [comment]
We can't use svg taller than 21px*21px. So I have to remove 

Wetland : https://github.com/gravitystorm/openstreetmap-carto/tree/master/symbols/generating_patterns/wetland.svg
Rock overlay : https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/generating_patterns/rock.svg
Military pattern : https://github.com/gravitystorm/openstreetmap-carto/blob/master/patterns/military_red_hatch.svg

from the sprites file.

**Comment by utagawal** [comment]
Cliff 1 also needed : https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/cliff.svg

**Comment by gqdc** [comment]
cliff.svg added to sprites

**Comment by utagawal** [comment]
fixed except for rocks pattern

**Comment by utagawal** [comment]
rock pattern fixed.

Closing issue
